spring:
  application:
    name: hotel-booking-api

  # AJOUTER CETTE LIGNE ICI POUR FIXER L'ERREUR DE BOOT
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_luxe
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

jwt:
  secret: ${JWT_SECRET:ma-cle-secrete-256-bits-minimum-pour-hmac}
  expiration: 86400000

app:
  security:
    mode: dev
  upload-dir: ./uploads/rooms
  frontend-url: http://localhost:4200
  # Configuration Groq
  ai-api-url: https://api.groq.com/openai/v1/chat/completions
  ai-api-key: ${GROQ_API_KEY}
  ai-model: llama-3.3-70b-versatile

server:
  port: 8080